"""Add farm_id foreign key to cultures table

Revision ID: 3d7af8bcde35
Revises: 05ea607f0ad0
Create Date: 2025-07-26 14:35:27.045887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7af8bcde35'
down_revision = '05ea607f0ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cultures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_id', sa.Integer(), nullable=True))  # Mudado para nullable=True temporariamente
        batch_op.create_foreign_key('fk_cultures_farm_id', 'farms', ['farm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cultures', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cultures_farm_id', type_='foreignkey')
        batch_op.drop_column('farm_id')

    # ### end Alembic commands ###
